class Attack{
    // C# Auto Implementation
    // real private Attribute is generated by Compiler
    public string name {get;}
    public int dmg {get;}
    public Attack(string name, int dmg){
        this.name = name;
        this.dmg = dmg;
    }
}